config/routes.rb
Rails.application.routes.draw do
  get 'publishers/index'

  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/edit'

  get 'publishers/show'

  get 'publishers/update'

  get 'publishers/destroy'

  get 'authors/index'

  get 'authors/new'

  get 'authors/create'

  get 'authors/edit'

  get 'authors/show'

  get 'authors/update'

  get 'authors/destroy'

  get 'categories/index'

  get 'categories/new'

  get 'categories/create'

  get 'categories/edit'

  get 'categories/show'

  get 'categories/update'

  get 'categories/destroy'

  get 'books/index'

  get 'books/new'

  get 'books/create'

  get 'books/edit'

  get 'books/show'

  get 'books/update'

  get 'books/destroy'

  get 'about/index'

  root 'books#index'

  get 'about' => 'about#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books

	validates :first_name, :last_name, presence: true,
					 length: {minimum: 2}
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :category
	belongs_to :author
	belongs_to :publisher

	validates :title, :category_id, :author_id, :publisher_id, :isbn, 
			  :price, :buy, :year, :format, :excerpt, :pages, 
			  presence: true
					
end

app/models/category.rb
class Category < ApplicationRecord	
	has_many :books

	validates :name, presence: true,
					 length: {minimum: 3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
	has_many :books

	validates :name, presence: true					
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title ="About Us"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @page_title = 'Add Author'
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
    flash[:notice] = "Author Created"

    redirect_to authors_path
    else
        render 'new'
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

       

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book_title = 'Add Book'
    @books =Book.all
  end

  def new
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book Created"

      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @book =Book.find(params[:id])
    @category = Category.all
    
  end

  def update
  end

  def destroy
  end

  private
  def book_params
    params.require(:book).permit(:title, :coverpath,:category_id, :author_id, :publisher_id, :isbn, :price, :buy, :year, :format, :excerpt, :pages)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @page_title = 'Add Category'
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
       if @category.save
        flash[:notice] = "Category Created"
         redirect_to categories_path
       else
        render 'new'
      end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
    @page_title = 'Add Publisher'
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher =Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher Created"

      redirect_to publishers_path
    else
      render 'new'  
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def publisher_params
    params.require(:publisher).permit(:name)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut rutrum felis, in egestas lacus. Sed convallis sagittis ligula, ac mollis dui posuere vitae. Sed id neque ornare, fermentum mauris pharetra, hendrerit sapien. Curabitur aliquam risus ipsum, vel bibendum ex luctus sagittis. Mauris elementum suscipit ante et egestas. Praesent sed leo elementum, faucibus est quis, euismod nunc. Duis pulvinar nisi non odio volutpat efficitur. Cras leo massa, ornare eu commodo mattis, placerat iaculis risus. Donec sed ligula sed felis elementum imperdiet a sit amet urna. Aliquam tempor, ex non luctus efficitur, augue sapien consequat ante, ut molestie dolor risus nec erat. Suspendisse faucibus odio vel felis vestibulum, ut bibendum dui sollicitudin. Integer dictum magna dui. Sed in libero iaculis, gravida augue et, consequat sem. Integer euismod semper ligula, at convallis ligula congue ullamcorper. Aenean at mollis quam, ut ornare enim.</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors#index</h1>
<p>Find me in app/views/authors/index.html.erb</p>

app/views/authors/new.html.erb
<h2>Add New Author</h2>

<%= form_for @author do |f| %>
<% if @author.errors.any? %>
	<% @author.errors.full_messages.each do |msg| %>
<!-- Show errors -->
		<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end %>

<div class="form-group">
	<%= f.label :first_name %><br>
	<%= f.text_field :first_name, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :last_name %><br>
	<%= f.text_field :last_name, class:"form-control" %><br>
</div>

<%= f.submit "Submit", class:"btn btn-primary" %>
<%= link_to "Cancel", authors_path, class:"btn btn-info" %>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div id="books-index">
	<% @books.each_slice(4) do |book| %>
		<div class="row">
			<% book.each do |book| %>
				<div class="col-md-3 col-sm-3">
					<h3><%= book.title %></h3>
					<%= image_tag(book.coverpath) %>
					<%= link_to 'Read More', book_path(book), class:"btn btn-default" %>
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for @book do |f| %>
<% if @book.errors.any? %>
	<% @book.errors.full_messages.each do |msg| %>
<!-- Show errors -->
		<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end %>

<div class="form-group">
	<%= f.label :title %><br>
	<%= f.text_field :title, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :isbn %><br>
	<%= f.text_field :isbn, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :category %><br>
	<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, 
	{:include_blank => 'Select One'}, class:"form-control" %><br><br>
</div>
<div class="form-group">
	<%= f.label :author %><br>
	<%= f.select :author_id, Author.all.collect {|x| [x.first_name + ' ' + x.last_name, x.id]}, 
	{:include_blank => 'Select One'}, class:"form-control" %><br><br>
</div>
<div class="form-group">
	<%= f.label :publisher %><br>
	<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, 
	{:include_blank => 'Select One'}, class:"form-control" %><br><br>
</div>
<div class="form-group">
	<%= f.label :format %><br>
	<%= f.text_field :format, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :excerpt %><br>
	<%= f.text_area :excerpt, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :pages %><br>
	<%= f.number_field :pages, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :year %><br>
	<%= f.text_field :year, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :coverpath %><br>
	<%= f.text_field :coverpath, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :price %><br>
	<%= f.text_field :price, class:"form-control" %><br>
</div>
<div class="form-group">
	<%= f.label :buy %><br>
	<%= f.text_field :buy, class:"form-control" %><br>
</div>

<%= f.submit "Submit", class:"btn btn-success" %>
<%= link_to "Cancel", books_path, class:"btn btn-danger" %>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
	<h2><%= @book.title %></h2>
	<div class="books-show-left">
		<%= image_tag(@book.coverpath) %>
	</div>
	<div class="books-show-right">
		<h3>Book Info: </h3>
		<ul>
		    <li><strong>Category:</strong> <%= @book.category.name %></li>
		    <li><strong>Author:</strong> <%= @book.author.first_name %> <%= @book.author.last_name %></li>
		    <li><strong>Publisher:</strong> <%= @book.publisher.name %></li>
		    <li><strong>Year:</strong> <%= @book.year %></li>
		    <li><strong>ISBN:</strong> <%= @book.isbn %></li>
		    <li><strong>Format:</strong> <%= @book.format %></li>
		    <li><strong>Pages:</strong> <%= @book.pages%></li>
		</ul>			
			<%= link_to 'Buy For ' + @book.price, @book.buy, class:"btn btn-success" %>

	</div>

	<div class="clearfix"></div>

		<h4>Excerpt</h4>
		<p><%= @book.excerpt %>		
		</p>	 
	
</div><%= link_to 'Go Back', books_path, class:"btn btn-info pull-right" %>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
<!-- Check for errors -->
<% if @category.errors.any? %>
	<% @category.errors.full_messages.each do |msg| %>
<!-- Show errors -->
		<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end %>

<div class="form-group">
	<%= f.label :name %><br>
	<%= f.text_field :name, class:"form-control" %><br>
</div>

<%= f.submit "Submit", class:"btn btn-primary" %>
<%= link_to "Cancel", categories_path, class:"btn btn-info" %>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><%= @page_title ? @page_title : 'Welcome'  %> | 'The BookStore'</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %></li>
            <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path %></li>           
          </ul>
          <ul class="nav navbar-nav navbar-right">
          	<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Book', new_book_path %></li>
            <li><%= link_to 'Category', new_category_path %></li>
            <li><%= link_to 'Author', new_author_path %></li>
            <li><%= link_to 'Publisher', new_publisher_path %></li>
           </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    	<%= render 'partials/header' %>	
    <section>
	    <div class="container">
	    	<div class="row">
	    		<div class="col-md-8">
            <%= render 'partials/flash_msg' %>
	    			<%= yield %>
	    		</div>
	    		<div class="col-md-4">
	    			<%= render 'partials/sidebar' %>
	    		</div>
	    	</div>		
	    </div>
	</section>
	<section>
	    
	    	<%= render 'partials/footer' %>	    		
	    
	</section>
   </div>
  </body>

</html>

app/views/partials/_flash_msg.html.erb
<% if flash[:notice] %>
<div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/partials/_footer.html.erb
<footer>
	<div class="container" align="center">
		<p>Copyright &copy; 2019, All Rights Reserved Codrin Popescu</p>
	</div>
</footer>

app/views/partials/_header.html.erb
<header>
    <div class="container">
    	<h1>The BookStore <small><%= @page_title ? @page_title : 'Welcome'  %></small></h1>
    </div>	
</header>

app/views/partials/_sidebar.html.erb

<% if params[:controller] == 'about' %>
<div class="well">
	<h3>Location Info</h3>
	<ul>
		<li>The BookStore</li>
		<li>111 Morieux Road</li>
		<li>London E10 7LJ</li>
		<li>Phone: 075700000</li>
		<li>Email: codin@ascheri.co.uk</li>
	</ul>
</div>
<% end %>
<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
<div class="list-group">
  <a href="#" class="list-group-item">Ruby On Rails</a>
  <a href="#" class="list-group-item">PHP</a>
  <a href="#" class="list-group-item">HTML5</a>  
</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h1>Publishers#edit</h1>
<p>Find me in app/views/publishers/edit.html.erb</p>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h2>Add New Publisher</h2>

<%= form_for @publisher do |f| %>
<% if @publisher.errors.any? %>
	<% @publisher.errors.full_messages.each do |msg| %>
<!-- Show errors -->
		<div class="alert alert-danger"><%= msg %></div>
	<% end %>
<% end %>

<div class="form-group">
	<%= f.label :name %><br>
	<%= f.text_field :name, class:"form-control" %><br>
</div>

<%= f.submit "Submit", class:"btn btn-primary" %>
<%= link_to "Cancel", publishers_path, class:"btn btn-info" %>
<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>